# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad85ebe51631842f18bc044065fe0f4575c65de073471fb740d646c92371c6c19ee89fb6c74afd00050013fb29439b4e8ac79496eeb45e1d0ea105be6a0e7a22

test:
  secret_key_base: 6ccd9bbfa2e304ed8f183bf88a0f2cd2bd2ae3c78638872851d2d2636dfed136f847b5405a5ec7a28358d4fc718e2ce3db2828cf128a36d0709d8bb789a20cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
